### ISSUE TITLE
Extra title in navigation

### ISSUE THREAD

**Issue by Serhioromano** [cjsheets/mkdocs-rtd-dropdown#11]
I think I missed repository by creating that issue

mkdocs/mkdocs#1374

I think this one is few seconds for you to fix and I'd referred to your template.

**Comment by cjsheets** [comment]
This issue was resolved by the latest merge. I ended up following the logic you laid out in the linked bug.

If there are 2+  H1 tags, they become drop-down menus.

If there is only 1 H1 tag, it is incorporated into the page title to avoid the duplicate drop-down.

There is still some work to be done to support document structures deeper than 2 levels, but this was a step in the right direction.

**Comment by koppor** [comment]
@cjsheets Would it be possible if the two H1 tags have the same content, the second one is ignored?

From a file `javafx.md` with heading `# JavaFX`, I get following output:

![grafik](https://user-images.githubusercontent.com/1366654/71935308-c228b000-31a6-11ea-9abe-32d167bbfd7e.png)

I think, the yellow heading can safely be removed from the output? Maybe, this is a rtd theme issue?
