### ISSUE TITLE
Navigation link busted (for me) - fix included

### ISSUE THREAD

**Issue by KristinaPlazonic** [cjsheets/mkdocs-rtd-dropdown#18]
site.xml would have correct links, but in index.html there would be a `/` added to the relative link. This would break the navigation. 

Here is a reproducible example: 
[repo](https://github.com/KristinaPlazonic/scratch4) 
[pages](https://kristinaplazonic.github.io/scratch4/)

The fix is to change nav.html file (in my anaconda this is /home/kris/anaconda3/lib/python3.6/site-packages/rtd_dropdown/nav.html) and replace the line `  {%- set child_url = nav_item.abs_url %} `  with `  {%- set child_url = nav_item.url %}`. 

Leaving this here just in case anybody else wants a fix. 

Otherwise, thanks for the theme, I really like that functionality (collapsible menus).

**Comment by cjsheets** [comment]
Thanks for the fix and the repro. Sorry I wasn't able to address the issue sooner.

MkDocs [recently released](https://github.com/mkdocs/mkdocs/releases) v.1.0 which included a number of breaking changes and enhancements for theme development. I re-wrote rtd-dropdown as a result.

Because of the re-write I'll close this issue. Thanks again!
