### ISSUE TITLE
Sidebar totally garbled with lots of pages

### ISSUE THREAD

**Issue by marcelstoer** [cjsheets/mkdocs-rtd-dropdown#2]
The theme fails to handle the documentation for https://github.com/nodemcu/nodemcu-firmware/. The sidebar is nearly empty when there should be lots of content. I turned off our `js/extra.js` to test but the behavior is the same.

**Comment by cjsheets** [comment]
That's also interesting. The theme isn't handling the `pages:` definition in the `*.yml` file very well.

If you adjusted the pages to match [this fork](https://github.com/cjsheets/nodemcu-firmware/blob/master/mkdocs.yml) you'd have 'some' support (here's [an example of the fork depoyed](http://nodemcu.sheets.ch)). I think there's still some work to do to fully support the mkdocs formats.

I'll leave this issue open and close it once I improve handling in this scenario. I should have time to clean it up before too long.

**Comment by marcelstoer** [comment]
Thanks for looking into this.

> If you adjusted the pages to match this fork

I see no commits from you, maybe you didn't push them?

> here's an example of the fork depoyed

I see other shortcomings with this. Would it be ok with you if I created new issues here for those or would you rather want me to wait until this one is resolved?

**Comment by cjsheets** [comment]
Oops, sorry, forgot to push my commits to the forked repo.

I updated the rtd-dropdown theme to improve support for different site structures. There are still a few javascript bugs I need to fix to make the menu expand/collapse when you click on labels (instead of forcing users to click the + / - symbol). The fork is now using the updated theme package ([http://nodemcu.sheets.ch](http://nodemcu.sheets.ch))

I'll need to experiment a bit more to figure out what the dropdown menu should look like in each situation. It's particularly tough to decide for deep-nested pages (like the Modules section) and shallow pages (like Overview).

To save time, let me get one more release out before opening additional issues. There are still a few clear problems I need to fix.

**Comment by cjsheets** [comment]
MkDocs recently released [version 1](https://github.com/mkdocs/mkdocs/releases) which improved theme support and allowed me to add deeper nesting.

I'm calling this fixed as of theme version 1.0.2
